application: zeneddit
version: 2
runtime: python27
api_version: 1
threadsafe: no

builtins:
- deferred: on

handlers:
- url: /test.*
  script: gaeunit.py

- url: /images/
  static_dir: images

- url: /js/
  static_dir: js

- url: /update_schema
  script: update_schema_handler.app  # path to webapp2 application definition.
  login: admin
  secure: always

- url: /.*
  script: main.py



