application: zennit-1087
version: 1
runtime: python27
api_version: 1
threadsafe: no

builtins:
- deferred: on

handlers:
- url: /test.*
  script: gaeunit.py

- url: /images/
  static_dir: images

- url: /js/
  static_dir: js

- url: /css/
  static_dir: css

- url: /update_schema
  script: update_schema_handler.app  # path to webapp2 application definition.
  login: admin
  secure: always

- url: /.*
  script: main.py



env_variables:
  REDIRECT_URL: 'http://zennit-1087.appspot.com/oauth_callback'
